### ISSUE TITLE
Caching issue when deleting keys in the UI

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#1660]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

Keys are cached in the UI and not revalidated when deleted

### Steps to Reproduce

1. Login and APIs -> select my proof-of-concept api & dashboard shows Total Keys 5
2. Click Keys tab & I see a list of 5 keys
3. Select the bottom most key -> settings -> delete key and confirm in the popup modal
4. Redirected back to API’s page, select proof-of-concept api again & dashboard shows Total Keys 4 as expected
5. Here’s the bug!  Click Keys tab & I see a list of… 5 keys including the one I just deleted and not 4:
6. If I click on the key again I get a 404 & pressing the back button in browser returns to the list, however, the key is still displayed
-- If I manually refresh the page it disappears and the list now has 4 as expected

### Expected behavior

It should not display deleted keys

### Version info

```markdown
does not apply
```

**Comment by bryan-queryai** [comment]
To further narrow this down the behavior may be somehow related to or caused by the presence of multiple unassigned (to a userId) keys in the list.

In the scenario above out of the 5 Keys; 3 had a userId and 2 did not.  Deleting 1 of the 2 without userId caused the problem as described where it remained in the list.  When I deleted the last unassigned key it did not remain in the list at step 5 above.
