### ISSUE TITLE
dashboard: Key Details UI needs two optimizations for mobile

### ISSUE THREAD

**Issue by guilhermerodz** [unkeyed/unkey#1989]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

![CleanShot 2024-07-29 at 08 01 57@2x](https://github.com/user-attachments/assets/336686ba-00d3-490c-a267-02872e24c42c)

![CleanShot 2024-07-29 at 08 01 39@2x](https://github.com/user-attachments/assets/418637fc-593c-44d2-b3b7-88a35800df99)

### Steps to Reproduce

1. Go to APIs > Keys then select a key and go into its details page.
2. You'll see overflowing elements on both key settings and key permissions pages.

### Expected behavior

There should be no overflowing elements in X axis for that screen.

### Version info

```markdown
- OS:
- Node:
- npm:
```

**Comment by harshsbhat** [comment]
I would like to work on this one

**Comment by sreeharsha-rav** [comment]
.take

**Comment by chronark** [comment]
go for it

**Comment by sreeharsha-rav** [comment]
I went through the code and implemented 2 changes:
1. Truncate the text so that you don't see overflow
2. Dynamic grid according to screen sizes
<img width="289" alt="image" src="https://github.com/user-attachments/assets/cacc67a7-755c-4580-bce5-75aaef910ea5">

https://github.com/user-attachments/assets/4a2778f5-45c6-45a1-88cf-b3f991d24b22




What do you think?
