### ISSUE TITLE
Add Discord + Support to the left navigation

### ISSUE THREAD

**Issue by perkinsjr** [unkeyed/unkey#2095]
Add the request support and a link to Discord, from the command + K to the sidebar. 

People are less likely to find that hidden feature that isn't advertised anywhere causing friction to find support or our discord.

**Comment by harshsbhat** [comment]
![image](https://github.com/user-attachments/assets/8302c35d-5e16-46f3-bb9c-fc2f6ee00741)

The icon is also not looking good in the dark mode. So, we will need to fix that as well

Also, the https://app.unkey.com/discord link is not redirecting to anything. It should ideally redirect to the server. By side bar I assume you mean below the vertical nav under `Resources`

**Comment by chronark** [comment]
it's `https://unkey.com/discord`

**Comment by harshsbhat** [comment]
> it's `https://unkey.com/discord`

I know but the` Commad + k` or` Control + k` has the issue I mentioned. If you click on the discord button here. It will redirect to  https://app.unkey.com/discord which is a 404 page.

`<CommandItem onSelect={() => router.push("/discord")}>`

It should be the actual link instead of /discord i.e https://discord.com/invite/fDbezjbJbD"

![image](https://github.com/user-attachments/assets/039f721b-e575-4270-a652-ff41c90d1504)

**Comment by chronark** [comment]
no, it should be `https://unkey.com/discord`

**Comment by harshsbhat** [comment]
Sure, I will make a PR for both this link and #2100 in 10-15 minutes.

**Comment by harshsbhat** [comment]
![image](https://github.com/user-attachments/assets/7a7d8a29-d09d-4c89-b33e-290ff52b75de)


WDYT?

**Comment by chronark** [comment]
We can keep it as "Resources", but adding the 2 links is good, yes
