### ISSUE TITLE
Auditlogs Filters can't press on filter

### ISSUE THREAD

**Issue by Flo4604** [unkeyed/unkey#2391]
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Issue Summary

I cannot press on any of the filter option in the audit log page except the system one, all events users and root keys are not clickable, only way to toggle them is via the keyboard

### Steps to Reproduce

1. Go into API with auditlogs
2. Try to filter with your mouse 

### Expected behavior

I would expect the filter options to be clickable

### Screenshots

https://preview.screen.studio/share/zCAzNHHP

### Version info

```markdown
-
```

**Comment by unrenamed** [comment]
@Flo4604 I can reproduce this on my side too. Although, in dev mode all filter options are active and selectable. Not sure about the root cause, but on production `https://app.unkey.com` all filter items contain `data-[disabled]` attribute which apply `opacity: .5` and `pointer-events: none` properties. Oddly, the `data-[disabled]` attribute is `false` 😄

**Comment by chronark** [comment]
yup, I can reproduce this
