### ISSUE TITLE
[KEY-261] Documentation link in the footer leads to a 404

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#579]
It should work actually, we have a rewrite in `/apps/web/next.config.js` 

Not sure why it doesn't rewrite but our `[...not-found]` page catches it

<sub>From [SyncLinear.com](https://synclinear.com) | [KEY-261](https://linear.app/unkey/issue/KEY-261/documentation-link-in-the-footer-leads-to-a-404)</sub>

**Comment by codingmickey** [comment]
I was looking into this and was checking if `/docs` worked instead of the whole URL.. but unfortunately, I have issues setting up the local env and not a Debit card at hand (for Planetscale LMAO) so you guys can try and check once
 
https://github.com/codingmickey/unkey/blob/6aa8c2b775e39a9ca7f8da88129f7d2f22ac8186/apps/web/components/landing/footer.tsx#L18
