### ISSUE TITLE
Feature Request: Full API Key Retrieval Option in Unkey

### ISSUE THREAD

**Issue by luisalrp** [unkeyed/unkey#658]
### Preliminary Checks

- [X] I have reviewed https://unkey.dev/docs for existing features that would solve my problem

- [X] I have searched for existing feature requests: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a feature request directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Is your feature request related to a problem? Please describe.

Problem: Currently, Unkey only provides the beginning portion of an API key when it is retrieved. This approach aligns with standard security practices where an API key is shown only once and the user is expected to store it securely. However, this approach presents a limitation in certain user scenarios.

User Scenario Impacted: In my specific use case, I need to provide clients with a URL that includes the API key as a parameter. This enables them to easily integrate it into client software and access my services. The current functionality of Unkey, which restricts the full visibility of the API key post-creation, hinders this process.

### Describe the solution

I propose the implementation of a feature where users have the option to retrieve the complete API key upon request. To maintain security standards, this could be implemented with additional safety measures, such as:

Access Logs: Maintain logs of when and by whom the complete API key is retrieved.
Restricted Access: Allow this feature only for users with specific roles or permissions.

### Rationale:
While I understand and appreciate the security concerns with displaying the full API key, providing a controlled, secure method for retrieving it can significantly enhance user experience in certain scenarios without compromising overall security. This feature will be particularly beneficial for users who need to provide API keys as part of integration URLs or in scenarios where secure, yet easy access to the full API key is necessary.

### Conclusion:
I believe this feature would be a valuable addition to Unkey, offering developers the flexibility to choose how to build their software while catering to a broader range of user needs. I look forward to your thoughts and feedback on this proposal.

**Comment by chronark** [comment]
This has been requested in the past and we probably need to find a good way to do it, that protects users as much as possible while offering a way for advanced usecases.

Regarding this specific usecase, I'd like to learn more about it.
Why do you need to share the apiKey in the url and would a short lived token work too?

**Comment by ethan-stone** [comment]
Just brainstorming how this could be implemented since it's interesting. For best security, it'd probably be best to use envelope encryption and a key management system and store the encrypted key in a completely separate table.

Envelope Encryption: https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#enveloping 

Maybe each workspace has its own data encryption key, and that is used to encrypt the API keys. The encrypted API keys are stored in a completely separate table so it doesn't sit next to the hashed API key.

**Comment by chronark** [comment]
Encryption per workspace is definitely good yeah. I'd maybe go as far and give the user the encryption key and not store it ourselves. Because if someone has access to one of our tables, we can assume the entire database is compromised, so we gained nothing.

The encryption keys must be stored outside of the database I think.

It's once again a tradeoff between security and user experience.

**Comment by perkinsjr** [comment]
Hey @luisalrp 

we introduced this feature called "vault" that allows you to now retrieve keys as you need.

https://www.unkey.com/docs/security/recovering-keys

It is opt in and not retroactive but allows you to get the full API key at anytime.
