### ISSUE TITLE
Workspace renaming doesn't show a loading indicator

### ISSUE THREAD

**Issue by chronark** [unkeyed/unkey#877]
### Preliminary Checks

- [X] I have reviewed the documentation: [https://unkey.dev/docs](https://unkey.dev/docs)
- [X] I have searched for existing issues: [https://github.com/unkeyed/unkey/issues](https://github.com/unkeyed/unkey/issues)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: [https://unkey.dev/discord](https://unkey.dev/discord).

### Reproduction / Replay Link (Optional)

*No response*

### Issue Summary

The "Save" button should show a loading spinner during the mutation

![CleanShot 2024-01-25 at 10 02 59](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/c8ad6747-2ad9-4a55-84b4-7ffb59fe2c61/220375c2-fe79-4f6f-8d0b-bb7184932bd0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS9jOGFkNjc0Ny0yYWQ5LTRhNTUtODRiNC03ZmZiNTlmZTJjNjEvMjIwMzc1YzItZmU3OS00ZjZmLThkMGItYmI3MTg0OTMyYmQwIiwiaWF0IjoxNzA2NDQ4MTAxLCJleHAiOjMzMjc3MDA4MTAxfQ.K13ubYrz3QQiX4HdvDGi_ETsB8WrwSZRQyLbTnStEJU)

### Steps to Reproduce

1. go to /app/settings/general
2. change the name of the workspace
3. click save

### Expected behavior

It should display a loading spinner

### Other information

*No response*

### Screenshots

*No response*

### Version info

```
- OS:
- Node:
- npm:
```

**Comment by ashrafchowdury** [comment]
**I would like to raise a PR for this bug** 🙌

**Comment by AkshayBandi027** [comment]
hey @chronark,
      I have noticed that **form.formState.isSubmitting** has been directly used without invoked or subscribed to.

  ` <Button
              variant={form.formState.isSubmitting ? "disabled" : "primary"}
              type="submit"
              disabled={form.formState.isSubmitting}
            >
              {form.formState.isSubmitting ? <Loading /> : "Save"}
            </Button>`

 official docs stats - **formState is wrapped with a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to improve render performance and skip extra logic if specific state is not subscribed to. Therefore make sure you invoke or read it before a render in order to enable the state update.**


But I have also tried to destruct the formState from form to read isSubmitting before using as the state update but it didn't work.

 `const {formState:{isSubmitting}} = form`
`<Button
            variant={isSubmitting ? "disabled" : "primary"}
            type="submit"
            disabled={isSubmitting}
          >
          {isSubmitting? <Loading /> : "Save"}
      </Button>`

We make use of react query's ***isLoading*** property from updateName mutation and It works. 

` <Button
              variant={updateName.isLoading ? "disabled" : "primary"}
              type="submit"
              disabled={updateName.isLoading}
            >
             {updateName.isLoading ? <Loading /> : "Save"}
            </Button>`

https://github.com/unkeyed/unkey/assets/100031493/33c3511e-25a6-407a-8a94-6aab82e2052d

**Comment by AkshayBandi027** [comment]
#925
